version: '3.8'

services:
  megaproxy:
    image: nginx:latest
    container_name: megaproxy
    volumes:
      - ./megaproxy.conf:/etc/nginx/nginx.conf      
      - ./certificates:/etc/nginx/certificates
    ports:
      - "80:80"
      - "443:443"
    networks:
      - megagera_network

networks:
  megagera_network:
    external: true
